export default [
  {
    firstName: 'Caresse',
    lastName: 'Allington',
    email: 'callington0@baidu.com',
    password: 'ZnKGy7jDOiQ',
    isActive: true,
  },
  {
    firstName: 'Jude',
    lastName: 'Red',
    email: 'jred1@livejournal.com',
    password: 'ENvLCA',
    isActive: true,
  },
  {
    firstName: 'Sasha',
    lastName: 'Blueman',
    email: 'sblueman2@bluehost.com',
    password: 'f313GdZ',
    isActive: true,
  },
  {
    firstName: 'Angie',
    lastName: 'Pollitt',
    email: 'apollitt3@irs.gov',
    password: 'Go8C5IZ',
    isActive: true,
  },
  {
    firstName: 'Teresina',
    lastName: 'Schankelborg',
    email: 'tschankelborg4@printfriendly.com',
    password: 'YCc4yF',
    isActive: false,
  },
  {
    firstName: 'Nerti',
    lastName: 'Jee',
    email: 'njee5@gov.uk',
    password: 'VB7SjJwpz',
    isActive: true,
  },
  {
    firstName: 'Wilek',
    lastName: 'Awty',
    email: 'wawty6@census.gov',
    password: 'fTK1uaDj',
    isActive: false,
  },
  {
    firstName: 'Stacey',
    lastName: 'Braund',
    email: 'sbraund7@cbsnews.com',
    password: 'pTsd51mr',
    isActive: false,
  },
  {
    firstName: 'Rosalie',
    lastName: 'Castella',
    email: 'rcastella8@lulu.com',
    password: '20VCfFk',
    isActive: false,
  },
  {
    firstName: 'Herman',
    lastName: 'Goodin',
    email: 'hgoodin9@fda.gov',
    password: 'VBpGiRHjhU6',
    isActive: true,
  },
];
